package tests

// This code is generated by 'csvgen'
// Do not edit

// Foo Unmarshaller func
func (this *Foo) UnmarshalCSV(in []string) error {}

// Foo Marshaller func
func (this Foo) MarshalCSV() (string, error) {}

// Boo Unmarshaller func
func (this *Boo) UnmarshalCSV(in []string) error {}

// Boo Marshaller func
func (this Boo) MarshalCSV() (string, error) {}
