package tests

import (
	json "encoding/json"
	errors "errors"
	strconv "strconv"
)

// This code is generated by 'csvgen'
// Do not edit

// Foo Unmarshaller func
func (this *Foo) UnmarshalCSV(in []string) error {
	i := 0
	this.a = in[i]
	i += 1
	if x, err := strconv.ParseInt(in[i], 64); err != nil {
		this.b = x
		return nil
	} else {
		return err
	}
	i += 1
	if x, err := strconv.ParseInt(in[i], 64); err != nil {
		this.c = x
		return nil
	} else {
		return err
	}
	i += 1
	if err := json.Unmarshal([]byte(in[i]), this.s); err != nil {
		return err
	}
}

// Foo Marshaller func
func (this Foo) MarshalCSV() (string, error) {}

// Boo Unmarshaller func
func (this *Boo) UnmarshalCSV(in []string) error {
	i := 0
	if x, err := strconv.ParseFloat(in[i], t64); err != nil {
		if this.a == nil {
			return errors.New("nil pointer found at a *float64")
		}
		*this.a = x
		return nil
	} else {
		return err
	}
	i += 1
	if this.b == nil {
		return errors.New("nil pointer found at b *string")
	}
	*this.b = in[i]
	i += 1
	if err := json.Unmarshal([]byte(in[i]), &this.z); err != nil {
		return err
	}
}

// Boo Marshaller func
func (this Boo) MarshalCSV() (string, error) {}
